import { SignUp } from "@/components/feature/SignUp/SignUp";
import styles from '@/pages/signup/index.module.css'
import Head from "next/head";

export default function index() {
  return (
    <>
      <Head>
        <title>SignUp</title>
        <meta name="description" content="Generated by SignUp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SignUp />
      </main>
    </>
  )
}